```@Project
styleID: 0
project:
  projectId: '8772'
  projectTagsShow: false
  projectMembersShow: false

```
#### 创作步骤
##### 第-步：定义模型部件函数
- 定义底座
 
 ![](https://api.keepwork.com/storage/v0/siteFiles/11650/raw#parameterized_func1.png) 

- 定义背面支架1
 
 ![](https://api.keepwork.com/storage/v0/siteFiles/11646/raw#parameterized_func2.png) 
 
- 定义中间支架2
 
 ![](https://api.keepwork.com/storage/v0/siteFiles/11647/raw#parameterized_func3.png) 

- 定义圆柱
 
 ![](https://api.keepwork.com/storage/v0/siteFiles/11649/raw#parameterized_func4.png) 


##### 第二步：定义建模参数
- 定义各个部件的基本大小参数
 
 ![](https://api.keepwork.com/storage/v0/siteFiles/11651/raw#parameterized_params.png)


##### 第三步：根据参数创建模型
- 创建各部件，并通布尔运算把各部件连接一起
 
 ![](https://api.keepwork.com/storage/v0/siteFiles/11653/raw#parameterized_make.png)
 ![](https://api.keepwork.com/storage/v0/siteFiles/11644/raw#parameterized.png)


#### 源代码

完整源代码请查看世界：https://keepwork.com/pbl/project/8772
```lua


function createBottom(length, height, width, corner, hole)
    pushNode("union", "object1", '#ff0000', true)
        box("union", length, height, width, '#ff0000')
        fillet({6,8}, corner)
        cylinder("difference", hole, height, '#ff0000')
        move(length/2 - corner, 0, -(width / 2 - corner));
        cylinder("difference", hole, height, '#ff0000')
        move(length/2 - corner, 0, width / 2 - corner);
    popNode()
end

function createBackSupporter(up, bottom, height, thickness)
    trapezoid("union",up,bottom,height,thickness,'#ff0000')
    rotate('y',90)
    move(0, height/2, 0)
end

function createCenterSupporter(up, bottom, height, thickness)
    polygon("union",{0,0,0, 0,height,0, up,height,0, bottom,0,0},'#ff0000')
    extrude(thickness)
    move(0,0,thickness/2)    
end

function createCylinder(radius, height)
    cylinder("union",radius,height,'#ff0000')
    rotate('z',90)
end


local bottom_length = 8;
local bottom_height = 2;
local bottom_width = 14;
local bottom_corner_radius = 2;
local bottom_hole_radius = 0.5;

local height = 10;
local backframe_thickness = 2;
local centerframe_thickness = 1;

local outer_radius = 3.5;
local inner_radius = 1.75;
local cylinder_length = 6.5;
local overflow = (outer_radius-inner_radius)*0.1;

createBottom(bottom_length, bottom_height, bottom_width, bottom_corner_radius, bottom_hole_radius)
move(0, bottom_height/2, 0)
pushNode("union", "object2", '#ff0000', true)
    createBackSupporter(cylinder_length, bottom_width, height, backframe_thickness)
    move(-(bottom_length-backframe_thickness)/2, bottom_height, 0)
    createCenterSupporter(cylinder_length-backframe_thickness, (bottom_length-backframe_thickness), height-outer_radius+overflow, centerframe_thickness)
    move(-(bottom_length/2-backframe_thickness), bottom_height, 0)
    createCylinder(outer_radius, cylinder_length)
    move(-(bottom_length-cylinder_length)/2, height+bottom_height, 0)
    pushNode("difference", "object3", '#ff0000', true)
        createCylinder(inner_radius, cylinder_length)
        move(-(bottom_length-cylinder_length)/2, height+bottom_height, 0)
    popNode()
popNode()

```